spring:
  application:
    name: inventoryservice
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: testUser
    password: testPassword
  h2:
    console:
      enabled: false
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always