version: '3.7'

services:

  postgresql:
    image: postgres:14
    container_name: postgresqlDB
    environment:
      POSTGRES_USER: smart2fridge
      POSTGRES_PASSWORD: 4711
      POSTGRES_DB: smart2fridgeDB
      LISTEN_ADDRESSES: localhost
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  fridgecontentservice:
    build: 
      context: ./fridgecontentservice
    image: fridgecontentservice
    container_name: fridgecontentservice
    ports:
      - "8080:8080"
    expose:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_started
    environment:
      POSTGRES_URL: postgresql
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: "smart2fridge"
      POSTGRES_PASSWORD: "4711"
      POSTGRES_DB: smart2fridgeDB
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 2