CREATE TABLE IF NOT EXISTS SNAPSHOT(
    ID SERIAL PRIMARY KEY,
    CAPTURE_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ITEM(
    ID SERIAL PRIMARY KEY,
    SNAPSHOT_ID INTEGER,
    DESCRIPTION VARCHAR(255) NOT NULL,
    AMOUNT INTEGER NOT NULL,
    CONSTRAINT FK_SNAPSHOT
        FOREIGN KEY(SNAPSHOT_ID)
        REFERENCES SNAPSHOT(ID)
        ON DELETE CASCADE
);
