###
DELETE http://localhost:8080/v1/item/bulk/67
Accept: application/json

###
GET http://localhost:8080/actuator/health
Accept: application/json

###
GET http://localhost:8080/v1/item/bulk/67
Accept: application/json

###
POST http://localhost:8080/v1/item/bulk
Content-Type: application/json

[
  {
    "description": "Banana"
  },
  {
    "description": "Apple"
  }
]

###
